### ISSUE TITLE
Attempted to assign to read-only property under Bun 0.1.8

### ISSUE THREAD

**Issue by robogeek** [Mogztter/asciidoctor-opal-node-runtime#168]
I'm trying to get my application (AkashaCMS) to run on Bun - the new Node.js-compatible platform.

At this line of code:

```js
const asciidoctor = require('@asciidoctor/core')();
```

I get this error:

```
$ bun filez.mjs 
Config start
1861 |       return Opal.send(this, body, args, block);
1862 |     };
1863 | 
1864 |     // Try to make the browser pick the right name
1865 |     alias.displayName       = name;
1866 |     alias.length            = body.length;
        ^
TypeError: Attempted to assign to readonly property.
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/asciidoctor-opal-runtime/src/opal.js:1866:4
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/asciidoctor-opal-runtime/src/opal.js:2806:4
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/asciidoctor-opal-runtime/src/opal.js:2311:6
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/asciidoctor-opal-runtime/src/opal.js:5466:2
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/asciidoctor-opal-runtime/src/opal.js:2311:6
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/asciidoctor-opal-runtime/src/opal.js:20066:2
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/asciidoctor-opal-runtime/src/opal.js:20075:44
      at bun:wrap:1:16354
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/asciidoctor-opal-runtime/src/index.js:23:10
      at bun:wrap:1:16354
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:2:21
      at bun:wrap:1:16354
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/akasharender/render-asciidoc.js:26:28
      at bun:wrap:1:16354
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/akasharender/index.js:177:42
      at bun:wrap:1:16354
      at /home/david/Projects/akasharender/akashacms-perftest/bench/config.mjs:6:0
```

**Comment by robogeek** [comment]
Here is a simple reproduction of the error, using your sample code:

```js
const asciidoctor = require('@asciidoctor/core')() // <1>
const content = 'http://asciidoctor.org[*Asciidoctor*] ' +
  'running on https://opalrb.com[_Opal_] ' +
  'brings AsciiDoc to Node.js!'
const html = asciidoctor.convert(content) // <2>
console.log(html) // <3>
```

```
$ bun asciidoctor.js 
1861 |       return Opal.send(this, body, args, block);
1862 |     };
1863 | 
1864 |     // Try to make the browser pick the right name
1865 |     alias.displayName       = name;
1866 |     alias.length            = body.length;
        ^
TypeError: Attempted to assign to readonly property.
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/asciidoctor-opal-runtime/src/opal.js:1866:4
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/asciidoctor-opal-runtime/src/opal.js:2806:4
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/asciidoctor-opal-runtime/src/opal.js:2311:6
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/asciidoctor-opal-runtime/src/opal.js:5466:2
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/asciidoctor-opal-runtime/src/opal.js:2311:6
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/asciidoctor-opal-runtime/src/opal.js:20066:2
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/asciidoctor-opal-runtime/src/opal.js:20075:44
      at bun:wrap:1:16354
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/asciidoctor-opal-runtime/src/index.js:23:10
      at bun:wrap:1:16354
      at /home/david/Projects/akasharender/akashacms-perftest/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:2:21
      at bun:wrap:1:16354
      at /home/david/Projects/akasharender/akashacms-perftest/bench/asciidoctor.js:1:28
```
